# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Landmark-remark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'KumulosSdkSwift', '~> 3.0'
  # Pods for Landmark-remark

  target 'Landmark-remarkTests' do
    inherit! :search_paths
    pod 'KumulosSdkSwift', '~> 3.0'
    # Pods for testing
  end

  target 'Landmark-remarkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
